//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a custom script from Strings.resx.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenameMusic.Resources.Languages
{
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Globalization;
    using System.Resources;

    [GeneratedCode("CustomResxGenerator", "1.0.0.0")]
    public class Strings
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        internal Strings()
        {
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                resourceMan ??= new ResourceManager("RenameMusic.Resources.Languages.Strings", typeof(Strings).Assembly);
                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string ADD_FILE => ResourceManager.GetString("ADD_FILE", resourceCulture)!;

        public static string ADD_FOLDER => ResourceManager.GetString("ADD_FOLDER", resourceCulture)!;

        public static string ADD_TAG => ResourceManager.GetString("ADD_TAG", resourceCulture)!;

        public static string ALBUM => ResourceManager.GetString("ALBUM", resourceCulture)!;

        public static string ALBUM_ARTIST => ResourceManager.GetString("ALBUM_ARTIST", resourceCulture)!;

        public static string ALL_MENTIONED => ResourceManager.GetString("ALL_MENTIONED", resourceCulture)!;

        public static string ALWAYS_RENAME_WITH_NUMBER => ResourceManager.GetString("ALWAYS_RENAME_WITH_NUMBER", resourceCulture)!;

        public static string ALWAYS_REPLACE => ResourceManager.GetString("ALWAYS_REPLACE", resourceCulture)!;

        public static string ALWAYS_SKIP => ResourceManager.GetString("ALWAYS_SKIP", resourceCulture)!;

        public static string APPLY => ResourceManager.GetString("APPLY", resourceCulture)!;

        public static string ARTIST => ResourceManager.GetString("ARTIST", resourceCulture)!;

        public static string ASK_EVERY_TIME => ResourceManager.GetString("ASK_EVERY_TIME", resourceCulture)!;

        public static string AUDIO_INFO_FORMAT => ResourceManager.GetString("AUDIO_INFO_FORMAT", resourceCulture)!;

        public static string CANCEL => ResourceManager.GetString("CANCEL", resourceCulture)!;

        public static string CANNOT_BE_EMPTY => ResourceManager.GetString("CANNOT_BE_EMPTY", resourceCulture)!;

        public static string COMMENT => ResourceManager.GetString("COMMENT", resourceCulture)!;

        public static string CONFLICT_POLICY => ResourceManager.GetString("CONFLICT_POLICY", resourceCulture)!;

        public static string CURRENT_FILE_NAME_MSG => ResourceManager.GetString("CURRENT_FILE_NAME_MSG", resourceCulture)!;

        public static string DARK => ResourceManager.GetString("DARK", resourceCulture)!;

        public static string DELETE_FILE => ResourceManager.GetString("DELETE_FILE", resourceCulture)!;

        public static string DELETE_FILE_CONFIRM_MSG => ResourceManager.GetString("DELETE_FILE_CONFIRM_MSG", resourceCulture)!;

        public static string DELETE_FOLDER => ResourceManager.GetString("DELETE_FOLDER", resourceCulture)!;

        public static string DELETE_FOLDER_CONFIRM_MSG => ResourceManager.GetString("DELETE_FOLDER_CONFIRM_MSG", resourceCulture)!;

        public static string DIRECTORY => ResourceManager.GetString("DIRECTORY", resourceCulture)!;

        public static string DO_NOT_RENAME => ResourceManager.GetString("DO_NOT_RENAME", resourceCulture)!;

        public static string DURATION => ResourceManager.GetString("DURATION", resourceCulture)!;

        public static string EDIT_TAGS => ResourceManager.GetString("EDIT_TAGS", resourceCulture)!;

        public static string ENGLISH => ResourceManager.GetString("ENGLISH", resourceCulture)!;

        public static string EXCEPTION_MSG => ResourceManager.GetString("EXCEPTION_MSG", resourceCulture)!;

        public static string EXIT => ResourceManager.GetString("EXIT", resourceCulture)!;

        public static string EXIT_MSG => ResourceManager.GetString("EXIT_MSG", resourceCulture)!;

        public static string FILE => ResourceManager.GetString("FILE", resourceCulture)!;

        public static string FILE_FILTER_FLAC_LABEL => ResourceManager.GetString("FILE_FILTER_FLAC_LABEL", resourceCulture)!;

        public static string FILE_FILTER_M4A_LABEL => ResourceManager.GetString("FILE_FILTER_M4A_LABEL", resourceCulture)!;

        public static string FILE_FILTER_MP3_LABEL => ResourceManager.GetString("FILE_FILTER_MP3_LABEL", resourceCulture)!;

        public static string FILE_FILTER_OGG_LABEL => ResourceManager.GetString("FILE_FILTER_OGG_LABEL", resourceCulture)!;

        public static string FILE_NOT_FOUND_MSG => ResourceManager.GetString("FILE_NOT_FOUND_MSG", resourceCulture)!;

        public static string FILE_NOT_FOUND_REMOVE_ONLY_MSG => ResourceManager.GetString("FILE_NOT_FOUND_REMOVE_ONLY_MSG", resourceCulture)!;

        public static string FILE_REPEATED_MSG => ResourceManager.GetString("FILE_REPEATED_MSG", resourceCulture)!;

        public static string FOLDERS => ResourceManager.GetString("FOLDERS", resourceCulture)!;

        public static string FOLDER_NOT_FOUND_REMOVE_ONLY_MSG => ResourceManager.GetString("FOLDER_NOT_FOUND_REMOVE_ONLY_MSG", resourceCulture)!;

        public static string GENRES => ResourceManager.GetString("GENRES", resourceCulture)!;

        public static string IMAGE_FILTER_GIF_LABEL => ResourceManager.GetString("IMAGE_FILTER_GIF_LABEL", resourceCulture)!;

        public static string IMAGE_FILTER_JPEG_LABEL => ResourceManager.GetString("IMAGE_FILTER_JPEG_LABEL", resourceCulture)!;

        public static string IMAGE_FILTER_PNG_LABEL => ResourceManager.GetString("IMAGE_FILTER_PNG_LABEL", resourceCulture)!;

        public static string IMAGE_FILTER_WEBP_LABEL => ResourceManager.GetString("IMAGE_FILTER_WEBP_LABEL", resourceCulture)!;

        public static string INVALID_TEMPLATE_MSG => ResourceManager.GetString("INVALID_TEMPLATE_MSG", resourceCulture)!;

        public static string KEEP_MY_CHOICE_MSG => ResourceManager.GetString("KEEP_MY_CHOICE_MSG", resourceCulture)!;

        public static string LANGUAGE => ResourceManager.GetString("LANGUAGE", resourceCulture)!;

        public static string LIGHT => ResourceManager.GetString("LIGHT", resourceCulture)!;

        public static string LOADED => ResourceManager.GetString("LOADED", resourceCulture)!;

        public static string LOADING => ResourceManager.GetString("LOADING", resourceCulture)!;

        public static string LOAD_PREV_DATA => ResourceManager.GetString("LOAD_PREV_DATA", resourceCulture)!;

        public static string LOCATION_MSG => ResourceManager.GetString("LOCATION_MSG", resourceCulture)!;

        public static string MAIN_WINDOW_TITLE => ResourceManager.GetString("MAIN_WINDOW_TITLE", resourceCulture)!;

        public static string METADATA_EDITOR => ResourceManager.GetString("METADATA_EDITOR", resourceCulture)!;

        public static string METADATA_EDIT_SUCCESS => ResourceManager.GetString("METADATA_EDIT_SUCCESS", resourceCulture)!;

        public static string MIN_TAG_REQ => ResourceManager.GetString("MIN_TAG_REQ", resourceCulture)!;

        public static string MISSING_FILES_TITLE => ResourceManager.GetString("MISSING_FILES_TITLE", resourceCulture)!;

        public static string MISSING_FILES_WARNING_MSG => ResourceManager.GetString("MISSING_FILES_WARNING_MSG", resourceCulture)!;

        public static string MISSING_TAGS_MODE => ResourceManager.GetString("MISSING_TAGS_MODE", resourceCulture)!;

        public static string MISSING_TAGS_RECALCULATE_CONFIRM_MSG => ResourceManager.GetString("MISSING_TAGS_RECALCULATE_CONFIRM_MSG", resourceCulture)!;

        public static string MISSING_TAGS_TITLE => ResourceManager.GetString("MISSING_TAGS_TITLE", resourceCulture)!;

        public static string MULTI_INSTANCE_MSG => ResourceManager.GetString("MULTI_INSTANCE_MSG", resourceCulture)!;

        public static string NAME => ResourceManager.GetString("NAME", resourceCulture)!;

        public static string NEW_NAME => ResourceManager.GetString("NEW_NAME", resourceCulture)!;

        public static string NONE_REQ => ResourceManager.GetString("NONE_REQ", resourceCulture)!;

        public static string NOT_ALLOWED => ResourceManager.GetString("NOT_ALLOWED", resourceCulture)!;

        public static string NO_CHANGES_APPLIED_MSG => ResourceManager.GetString("NO_CHANGES_APPLIED_MSG", resourceCulture)!;

        public static string ONLY_MARKED_ONES => ResourceManager.GetString("ONLY_MARKED_ONES", resourceCulture)!;

        public static string OPEN_IN_EXPLORER => ResourceManager.GetString("OPEN_IN_EXPLORER", resourceCulture)!;

        public static string PLAY_FILE => ResourceManager.GetString("PLAY_FILE", resourceCulture)!;

        public static string PREVIOUS_SESSION_DELETE_MSG => ResourceManager.GetString("PREVIOUS_SESSION_DELETE_MSG", resourceCulture)!;

        public static string PREVIOUS_SESSION_FOUND_MSG => ResourceManager.GetString("PREVIOUS_SESSION_FOUND_MSG", resourceCulture)!;

        public static string PREVIOUS_SESSION_TITLE => ResourceManager.GetString("PREVIOUS_SESSION_TITLE", resourceCulture)!;

        public static string READY => ResourceManager.GetString("READY", resourceCulture)!;

        public static string REASON => ResourceManager.GetString("REASON", resourceCulture)!;

        public static string REASON_EMPTY_PROPOSED_FILE_NAME => ResourceManager.GetString("REASON_EMPTY_PROPOSED_FILE_NAME", resourceCulture)!;

        public static string REASON_GENERIC_ERROR_FORMAT => ResourceManager.GetString("REASON_GENERIC_ERROR_FORMAT", resourceCulture)!;

        public static string REASON_MANUALLY_EXCLUDED => ResourceManager.GetString("REASON_MANUALLY_EXCLUDED", resourceCulture)!;

        public static string REASON_MISSING_REQUIRED_TAGS_FORMAT => ResourceManager.GetString("REASON_MISSING_REQUIRED_TAGS_FORMAT", resourceCulture)!;

        public static string REASON_TEMPLATE_EMPTY_NAME => ResourceManager.GetString("REASON_TEMPLATE_EMPTY_NAME", resourceCulture)!;

        public static string REASON_TEMPLATE_REQUIRES_TAG => ResourceManager.GetString("REASON_TEMPLATE_REQUIRES_TAG", resourceCulture)!;

        public static string REASON_UNKNOWN => ResourceManager.GetString("REASON_UNKNOWN", resourceCulture)!;

        public static string REASON_UNREADABLE_METADATA => ResourceManager.GetString("REASON_UNREADABLE_METADATA", resourceCulture)!;

        public static string REMOVE_FOLDER_CONFIRM_MSG => ResourceManager.GetString("REMOVE_FOLDER_CONFIRM_MSG", resourceCulture)!;

        public static string REMOVE_FROM_LIST => ResourceManager.GetString("REMOVE_FROM_LIST", resourceCulture)!;

        public static string RENAME => ResourceManager.GetString("RENAME", resourceCulture)!;

        public static string RENAME_ALL_CONFIRM_MSG => ResourceManager.GetString("RENAME_ALL_CONFIRM_MSG", resourceCulture)!;

        public static string RENAME_FILES => ResourceManager.GetString("RENAME_FILES", resourceCulture)!;

        public static string RENAME_SINGLE_CONFIRM_MSG => ResourceManager.GetString("RENAME_SINGLE_CONFIRM_MSG", resourceCulture)!;

        public static string RENAME_THIS_NOW => ResourceManager.GetString("RENAME_THIS_NOW", resourceCulture)!;

        public static string REPEATED_FILE => ResourceManager.GetString("REPEATED_FILE", resourceCulture)!;

        public static string REPLACE => ResourceManager.GetString("REPLACE", resourceCulture)!;

        public static string REPLACE_WITH => ResourceManager.GetString("REPLACE_WITH", resourceCulture)!;

        public static string REQ_TAG_MISS_MSG => ResourceManager.GetString("REQ_TAG_MISS_MSG", resourceCulture)!;

        public static string RESTARTING => ResourceManager.GetString("RESTARTING", resourceCulture)!;

        public static string RESTORE_SETTINGS => ResourceManager.GetString("RESTORE_SETTINGS", resourceCulture)!;

        public static string RULE_NOT_SATISFIED_MSG => ResourceManager.GetString("RULE_NOT_SATISFIED_MSG", resourceCulture)!;

        public static string RW_DESCRIPTION => ResourceManager.GetString("RW_DESCRIPTION", resourceCulture)!;

        public static string SAVE => ResourceManager.GetString("SAVE", resourceCulture)!;

        public static string SEARCH_SUBFOLDERS => ResourceManager.GetString("SEARCH_SUBFOLDERS", resourceCulture)!;

        public static string SETTINGS => ResourceManager.GetString("SETTINGS", resourceCulture)!;

        public static string SETTINGS_RESTORED => ResourceManager.GetString("SETTINGS_RESTORED", resourceCulture)!;

        public static string SKIP => ResourceManager.GetString("SKIP", resourceCulture)!;

        public static string SPANISH => ResourceManager.GetString("SPANISH", resourceCulture)!;

        public static string STRICT => ResourceManager.GetString("STRICT", resourceCulture)!;

        public static string SUMMARY_ADDED => ResourceManager.GetString("SUMMARY_ADDED", resourceCulture)!;

        public static string SUMMARY_DONE => ResourceManager.GetString("SUMMARY_DONE", resourceCulture)!;

        public static string SUMMARY_DUPLICATES_IGNORED => ResourceManager.GetString("SUMMARY_DUPLICATES_IGNORED", resourceCulture)!;

        public static string SUMMARY_FAILED => ResourceManager.GetString("SUMMARY_FAILED", resourceCulture)!;

        public static string SUMMARY_MISSING => ResourceManager.GetString("SUMMARY_MISSING", resourceCulture)!;

        public static string SUMMARY_SKIPPED => ResourceManager.GetString("SUMMARY_SKIPPED", resourceCulture)!;

        public static string SUMMARY_UNREADABLE_METADATA => ResourceManager.GetString("SUMMARY_UNREADABLE_METADATA", resourceCulture)!;

        public static string SUPPORTED_FILES => ResourceManager.GetString("SUPPORTED_FILES", resourceCulture)!;

        public static string TEMPLATE_NEEDS_TAG_MSG => ResourceManager.GetString("TEMPLATE_NEEDS_TAG_MSG", resourceCulture)!;

        public static string TEMPLATE_RECALCULATE_CONFIRM_MSG => ResourceManager.GetString("TEMPLATE_RECALCULATE_CONFIRM_MSG", resourceCulture)!;

        public static string TEMPLATE_REPEATED_TAGS_MSG => ResourceManager.GetString("TEMPLATE_REPEATED_TAGS_MSG", resourceCulture)!;

        public static string THEME => ResourceManager.GetString("THEME", resourceCulture)!;

        public static string TITLE => ResourceManager.GetString("TITLE", resourceCulture)!;

        public static string TOGGLE_LANG_MSG => ResourceManager.GetString("TOGGLE_LANG_MSG", resourceCulture)!;

        public static string TO_RENAME => ResourceManager.GetString("TO_RENAME", resourceCulture)!;

        public static string TRACK_NUM => ResourceManager.GetString("TRACK_NUM", resourceCulture)!;

        public static string TYPE => ResourceManager.GetString("TYPE", resourceCulture)!;

        public static string UNKNOWN => ResourceManager.GetString("UNKNOWN", resourceCulture)!;

        public static string USE_UNKNOWN_OR_TRANSLATED => ResourceManager.GetString("USE_UNKNOWN_OR_TRANSLATED", resourceCulture)!;

        public static string YEAR => ResourceManager.GetString("YEAR", resourceCulture)!;
    }
}
