<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>RenameMusic</RootNamespace>
    <StartupObject>RenameMusic.App</StartupObject>
    <UseWPF>true</UseWPF>
    <StartupObject>RenameMusic.App</StartupObject>
    <ApplicationIcon>Resources\Icons\icon.ico</ApplicationIcon>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <OutputType>WinExe</OutputType>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <TargetFramework>net6.0-windows7.0</TargetFramework>
    <PublishSingleFile>false</PublishSingleFile>
    <RuntimeIdentifiers>win-x86; win-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.7" />
    <PackageReference Include="taglib-sharp-netstandard2.0" Version="2.1.0" />
    <PackageReference Include="WinCopies.WindowsAPICodePack.Shell" Version="2.12.0.2" />
  </ItemGroup>
</Project>