//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenameMusic.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RenameMusic.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file.
        /// </summary>
        public static string ADD_FILE {
            get {
                return ResourceManager.GetString("ADD_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder.
        /// </summary>
        public static string ADD_FOLDER {
            get {
                return ResourceManager.GetString("ADD_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string ALBUM {
            get {
                return ResourceManager.GetString("ALBUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album artist.
        /// </summary>
        public static string ALBUM_ARTIST {
            get {
                return ResourceManager.GetString("ALBUM_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ARTIST {
            get {
                return ResourceManager.GetString("ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CHECK_UPDATES {
            get {
                return ResourceManager.GetString("CHECK_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current name:.
        /// </summary>
        public static string CURRENT_FILE_NAME_MSG {
            get {
                return ResourceManager.GetString("CURRENT_FILE_NAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string DIRECTORY {
            get {
                return ResourceManager.GetString("DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t rename.
        /// </summary>
        public static string DO_NOT_RENAME {
            get {
                return ResourceManager.GetString("DO_NOT_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string DURATION {
            get {
                return ResourceManager.GetString("DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, please notify the developer..
        /// </summary>
        public static string EXCEPTION_MSG {
            get {
                return ResourceManager.GetString("EXCEPTION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit?.
        /// </summary>
        public static string EXIT_MSG {
            get {
                return ResourceManager.GetString("EXIT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string EXPORT_SETTINGS {
            get {
                return ResourceManager.GetString("EXPORT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        public static string FILE_NOT_FOUND_MSG {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a file with the same name in this location. How do you want to continue?.
        /// </summary>
        public static string FILE_REPEATED_MSG {
            get {
                return ResourceManager.GetString("FILE_REPEATED_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string FOLDERS {
            get {
                return ResourceManager.GetString("FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string IMPORT_SETTINGS {
            get {
                return ResourceManager.GetString("IMPORT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template contains invalid characters and cannot be used as file name..
        /// </summary>
        public static string INVALID_TEMPLATE_MSG {
            get {
                return ResourceManager.GetString("INVALID_TEMPLATE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep my choice with the next files..
        /// </summary>
        public static string KEEP_MY_CHOICE_MSG {
            get {
                return ResourceManager.GetString("KEEP_MY_CHOICE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load previous data.
        /// </summary>
        public static string LOAD_PREV_DATA {
            get {
                return ResourceManager.GetString("LOAD_PREV_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string LOADED {
            get {
                return ResourceManager.GetString("LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string LOCATION_MSG {
            get {
                return ResourceManager.GetString("LOCATION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple instances of this program are not allowed..
        /// </summary>
        public static string MULTI_INSTANCE_MSG {
            get {
                return ResourceManager.GetString("MULTI_INSTANCE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string NEW_NAME {
            get {
                return ResourceManager.GetString("NEW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed.
        /// </summary>
        public static string NOT_ALLOWED {
            get {
                return ResourceManager.GetString("NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string READY {
            get {
                return ResourceManager.GetString("READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RENAME {
            get {
                return ResourceManager.GetString("RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename files.
        /// </summary>
        public static string RENAME_FILES {
            get {
                return ResourceManager.GetString("RENAME_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming Rule.
        /// </summary>
        public static string RENAMING_RULE {
            get {
                return ResourceManager.GetString("RENAMING_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the required tags which should not be empty fields, this helps to define which files will be renamed later..
        /// </summary>
        public static string RENAMING_RULE_DESCRIPTION {
            get {
                return ResourceManager.GetString("RENAMING_RULE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated file.
        /// </summary>
        public static string REPEATED_FILE {
            get {
                return ResourceManager.GetString("REPEATED_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string REPLACE {
            get {
                return ResourceManager.GetString("REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting....
        /// </summary>
        public static string RESTARTING {
            get {
                return ResourceManager.GetString("RESTARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RESTORE_SETTINGS {
            get {
                return ResourceManager.GetString("RESTORE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in subfolders.
        /// </summary>
        public static string SEARCH_SUBFOLDERS {
            get {
                return ResourceManager.GetString("SEARCH_SUBFOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings restored..
        /// </summary>
        public static string SETTINGS_RESTORED {
            get {
                return ResourceManager.GetString("SETTINGS_RESTORED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SKIP {
            get {
                return ResourceManager.GetString("SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task completed successfully..
        /// </summary>
        public static string TASK_SUCCESFULL_MSG {
            get {
                return ResourceManager.GetString("TASK_SUCCESFULL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string THEME {
            get {
                return ResourceManager.GetString("THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To rename.
        /// </summary>
        public static string TO_RENAME {
            get {
                return ResourceManager.GetString("TO_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will restart and the selected language will be applied..
        /// </summary>
        public static string TOGGLE_LANG_MSG {
            get {
                return ResourceManager.GetString("TOGGLE_LANG_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Nº.
        /// </summary>
        public static string TRACK_NUM {
            get {
                return ResourceManager.GetString("TRACK_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View help.
        /// </summary>
        public static string VIEW_HELP {
            get {
                return ResourceManager.GetString("VIEW_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
