name: "Deploy RM Project"

on:
  push:
    tags:
      - "RM/v*"

env:
  PROJECT_PATH: RenameMusic\RenameMusic.csproj

jobs:
  deploy:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86, x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore --runtime ${{ matrix.arch }}

      - name: Zip
        run: |
          7z a -r -tzip "RenameMusic_${{ matrix.arch }}.zip" "./RenameMusic/bin/Release/net6.0-windows-${{ matrix.arch }}/publish/*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: RenameMusic_${{ matrix.arch }}.zip
          path: RenameMusic_${{ matrix.arch }}.zip

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: RenameMusic_x86.zip
          asset_name: RenameMusic_x86.zip
          asset_content_type: application/zip

      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: RenameMusic_x64.zip
          asset_name: RenameMusic_x64.zip
          asset_content_type: application/zip
